# Generated by Django 2.2 on 2022-02-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mail',
            new_name='name',
        ),
    ]
